@echo off
echo Starting backend server...
start cmd /k "cd backend && npm start"
echo Waiting for backend to initialize...
timeout /t 5
echo Starting frontend server...
start cmd /k "cd frontend && npm start"
echo Development servers started!