// Restaurant-specific menu items with unique images
import { getUniqueMenuItemImage } from './uniqueMenuImages';

export const getRestaurantMenu = (restaurantId) => {
  const restNumber = parseInt(restaurantId.replace('rest', '')) || 0;
  
  let menuType = 'default';
  
  if ([1, 39, 42, 43, 46, 52, 57].includes(restNumber)) {
    menuType = 'italian';
  } else if ([3, 14, 25, 32, 33, 34, 35, 49, 50, 51, 55, 58].includes(restNumber)) {
    menuType = 'asian';
  } else if ([2, 19, 31, 38, 44, 48, 54].includes(restNumber)) {
    menuType = 'indian';
  } else if ([4, 6, 7, 9, 10, 11, 12, 18, 23, 24, 27, 29, 45, 47, 56].includes(restNumber)) {
    menuType = 'brewery';
  } else if ([5, 8, 13, 15, 21, 22, 40].includes(restNumber)) {
    menuType = 'fine_dining';
  } else if ([20, 36, 37, 53, 59].includes(restNumber)) {
    menuType = 'seafood';
  } else if ([16, 17, 26, 28, 30].includes(restNumber)) {
    menuType = 'thai_vietnamese';
  } else if ([60].includes(restNumber)) {
    menuType = 'continental';
  } else if ([41].includes(restNumber)) {
    menuType = 'middle_eastern';
  }
  
  const menus = {
    italian: {
      _id: `menu-${restaurantId}`,
      name: 'Italian Menu',
      categories: ['Appetizers', 'Pasta', 'Pizza', 'Risotto', 'Meat & Seafood', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Bruschetta', description: 'Grilled bread with tomatoes and basil', price: 1.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Appetizers'), isVegetarian: true },
        { _id: `item2-${restaurantId}`, name: 'Calamari Fritti', description: 'Crispy fried calamari with marinara sauce', price: 2.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Appetizers') },
        { _id: `item3-${restaurantId}`, name: 'Caprese Salad', description: 'Fresh mozzarella, tomatoes, and basil', price: 1.79, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Appetizers'), isVegetarian: true },
        { _id: `item4-${restaurantId}`, name: 'Antipasto Platter', description: 'Selection of cured meats and cheeses', price: 2.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Appetizers') },
        { _id: `item5-${restaurantId}`, name: 'Garlic Bread', description: 'Toasted bread with garlic butter', price: 0.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Appetizers'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Arancini', description: 'Fried rice balls with cheese', price: 1.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Appetizers'), isVegetarian: true },
        { _id: `item27-${restaurantId}`, name: 'Focaccia Bread', description: 'Herb-topped Italian flatbread', price: 1.29, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Appetizers'), isVegetarian: true },
        { _id: `item45-${restaurantId}`, name: 'Prosciutto e Melone', description: 'Parma ham with cantaloupe melon', price: 2.79, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item45', 'Appetizers') },
        { _id: `item46-${restaurantId}`, name: 'Vitello Tonnato', description: 'Sliced veal with tuna sauce', price: 3.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item46', 'Appetizers') },
        { _id: `item47-${restaurantId}`, name: 'Burrata', description: 'Creamy mozzarella with tomatoes', price: 2.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item47', 'Appetizers'), isVegetarian: true },
        { _id: `item6-${restaurantId}`, name: 'Spaghetti Carbonara', description: 'Classic pasta with eggs, cheese, and pancetta', price: 3.49, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Pasta') },
        { _id: `item7-${restaurantId}`, name: 'Fettuccine Alfredo', description: 'Creamy parmesan sauce with fettuccine', price: 3.29, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Pasta'), isVegetarian: true },
        { _id: `item8-${restaurantId}`, name: 'Lasagna', description: 'Layers of pasta, cheese, and bolognese sauce', price: 3.99, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Pasta') },
        { _id: `item9-${restaurantId}`, name: 'Penne Arrabbiata', description: 'Spicy tomato sauce with garlic and chili', price: 2.99, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Pasta'), isVegetarian: true },
        { _id: `item10-${restaurantId}`, name: 'Ravioli', description: 'Cheese-filled pasta with tomato sauce', price: 3.49, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Pasta'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'Spaghetti Bolognese', description: 'Traditional meat sauce with spaghetti', price: 3.29, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Pasta') },
        { _id: `item29-${restaurantId}`, name: 'Penne Pesto', description: 'Basil pesto sauce with pine nuts', price: 2.99, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item29', 'Pasta'), isVegetarian: true },
        { _id: `item30-${restaurantId}`, name: 'Linguine Seafood', description: 'Mixed seafood with white wine sauce', price: 4.49, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item30', 'Pasta') },
        { _id: `item11-${restaurantId}`, name: 'Margherita Pizza', description: 'Tomato sauce, mozzarella, and fresh basil', price: 2.99, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Pizza'), isVegetarian: true },
        { _id: `item12-${restaurantId}`, name: 'Pepperoni Pizza', description: 'Classic pizza with pepperoni', price: 3.49, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Pizza') },
        { _id: `item13-${restaurantId}`, name: 'Quattro Formaggi', description: 'Four cheese pizza', price: 3.79, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Pizza'), isVegetarian: true },
        { _id: `item14-${restaurantId}`, name: 'Vegetarian Pizza', description: 'Fresh vegetables and olives', price: 3.29, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Pizza'), isVegetarian: true },
        { _id: `item15-${restaurantId}`, name: 'Meat Lovers Pizza', description: 'Pepperoni, sausage, and ham', price: 4.49, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Pizza') },
        { _id: `item31-${restaurantId}`, name: 'Hawaiian Pizza', description: 'Ham and pineapple with cheese', price: 3.49, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item31', 'Pizza') },
        { _id: `item32-${restaurantId}`, name: 'BBQ Chicken Pizza', description: 'BBQ sauce, chicken, and red onions', price: 3.99, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item32', 'Pizza') },
        { _id: `item33-${restaurantId}`, name: 'Mushroom Pizza', description: 'Fresh mushrooms with garlic', price: 2.99, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item33', 'Pizza'), isVegetarian: true },
        { _id: `item48-${restaurantId}`, name: 'Prosciutto Pizza', description: 'Thin crust with prosciutto and arugula', price: 4.29, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item48', 'Pizza') },
        { _id: `item49-${restaurantId}`, name: 'Seafood Pizza', description: 'Mixed seafood with white sauce', price: 4.99, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item49', 'Pizza') },
        { _id: `item50-${restaurantId}`, name: 'Truffle Pizza', description: 'Truffle oil with wild mushrooms', price: 5.49, category: 'Pizza', image: getUniqueMenuItemImage(restaurantId, 'item50', 'Pizza'), isVegetarian: true },
        { _id: `item51-${restaurantId}`, name: 'Risotto Mushroom', description: 'Creamy arborio rice with porcini mushrooms', price: 3.99, category: 'Risotto', image: getUniqueMenuItemImage(restaurantId, 'item51', 'Risotto'), isVegetarian: true },
        { _id: `item52-${restaurantId}`, name: 'Risotto Seafood', description: 'Arborio rice with mixed seafood', price: 4.99, category: 'Risotto', image: getUniqueMenuItemImage(restaurantId, 'item52', 'Risotto') },
        { _id: `item53-${restaurantId}`, name: 'Risotto Saffron', description: 'Classic Milanese risotto with saffron', price: 4.49, category: 'Risotto', image: getUniqueMenuItemImage(restaurantId, 'item53', 'Risotto'), isVegetarian: true },
        { _id: `item54-${restaurantId}`, name: 'Osso Buco', description: 'Braised veal shanks with vegetables', price: 6.99, category: 'Meat & Seafood', image: getUniqueMenuItemImage(restaurantId, 'item54', 'Meat & Seafood') },
        { _id: `item55-${restaurantId}`, name: 'Saltimbocca', description: 'Veal with prosciutto and sage', price: 5.99, category: 'Meat & Seafood', image: getUniqueMenuItemImage(restaurantId, 'item55', 'Meat & Seafood') },
        { _id: `item56-${restaurantId}`, name: 'Branzino', description: 'Grilled sea bass with herbs', price: 5.49, category: 'Meat & Seafood', image: getUniqueMenuItemImage(restaurantId, 'item56', 'Meat & Seafood') },
        { _id: `item16-${restaurantId}`, name: 'Tiramisu', description: 'Coffee-soaked ladyfingers with mascarpone', price: 1.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Desserts'), isVegetarian: true },
        { _id: `item17-${restaurantId}`, name: 'Panna Cotta', description: 'Vanilla cream dessert with berry compote', price: 1.79, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Desserts'), isVegetarian: true },
        { _id: `item18-${restaurantId}`, name: 'Cannoli', description: 'Crispy pastry with ricotta cream', price: 1.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Desserts'), isVegetarian: true },
        { _id: `item19-${restaurantId}`, name: 'Gelato', description: 'Italian ice cream - various flavors', price: 1.29, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Desserts'), isVegetarian: true },
        { _id: `item20-${restaurantId}`, name: 'Chocolate Cake', description: 'Rich chocolate cake with ganache', price: 1.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Desserts'), isVegetarian: true },
        { _id: `item36-${restaurantId}`, name: 'Affogato', description: 'Gelato drowned in hot espresso', price: 1.79, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item36', 'Desserts'), isVegetarian: true },
        { _id: `item37-${restaurantId}`, name: 'Biscotti', description: 'Crunchy almond cookies', price: 0.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item37', 'Desserts'), isVegetarian: true },
        { _id: `item57-${restaurantId}`, name: 'Zabaglione', description: 'Light custard with Marsala wine', price: 2.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item57', 'Desserts'), isVegetarian: true },
        { _id: `item58-${restaurantId}`, name: 'Semifreddo', description: 'Italian frozen dessert with berries', price: 2.79, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item58', 'Desserts'), isVegetarian: true },
        { _id: `item21-${restaurantId}`, name: 'Espresso', description: 'Strong Italian coffee', price: 0.79, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Beverages'), isVegetarian: true },
        { _id: `item22-${restaurantId}`, name: 'Cappuccino', description: 'Espresso with steamed milk and foam', price: 1.29, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Beverages'), isVegetarian: true },
        { _id: `item23-${restaurantId}`, name: 'Italian Soda', description: 'Sparkling water with fruit syrup', price: 0.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Beverages'), isVegetarian: true },
        { _id: `item24-${restaurantId}`, name: 'Fresh Lemonade', description: 'Freshly squeezed lemon juice', price: 0.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Beverages'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Iced Tea', description: 'Refreshing iced tea with lemon', price: 0.89, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Beverages'), isVegetarian: true },
        { _id: `item34-${restaurantId}`, name: 'Americano', description: 'Espresso with hot water', price: 0.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item34', 'Beverages'), isVegetarian: true },
        { _id: `item35-${restaurantId}`, name: 'Latte', description: 'Espresso with steamed milk', price: 1.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item35', 'Beverages'), isVegetarian: true },
        { _id: `item59-${restaurantId}`, name: 'Limoncello', description: 'Traditional Italian lemon liqueur', price: 2.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item59', 'Beverages'), isVegetarian: true },
        { _id: `item60-${restaurantId}`, name: 'Chianti Wine', description: 'Classic Tuscan red wine', price: 3.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item60', 'Beverages'), isVegetarian: true }
      ]
    },
    
    indian: {
      _id: `menu-${restaurantId}`,
      name: 'Indian Menu',
      categories: ['Starters', 'Main Course', 'Tandoor', 'Breads', 'Rice', 'Street Food', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Vegetable Samosa (2 pcs)', description: 'Crispy pastry with spiced potatoes', price: 0.99, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Starters'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item2-${restaurantId}`, name: 'Paneer Tikka', description: 'Grilled cottage cheese with spices', price: 1.99, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Starters'), isVegetarian: true, spicyLevel: 2 },
        { _id: `item3-${restaurantId}`, name: 'Chicken Tikka', description: 'Marinated grilled chicken pieces', price: 2.29, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Starters'), spicyLevel: 2 },
        { _id: `item4-${restaurantId}`, name: 'Aloo Tikki', description: 'Crispy potato patties with chutneys', price: 0.79, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Starters'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item5-${restaurantId}`, name: 'Pakoras', description: 'Mixed vegetable fritters', price: 1.29, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Starters'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item31-${restaurantId}`, name: 'Chaat Papdi', description: 'Crispy wafers with yogurt and chutneys', price: 1.49, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item31', 'Starters'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item32-${restaurantId}`, name: 'Dahi Vada', description: 'Lentil dumplings in yogurt', price: 1.29, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item32', 'Starters'), isVegetarian: true },
        { _id: `item6-${restaurantId}`, name: 'Butter Chicken', description: 'Creamy tomato-based chicken curry', price: 2.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Main Course'), spicyLevel: 1 },
        { _id: `item7-${restaurantId}`, name: 'Palak Paneer', description: 'Cottage cheese in spinach sauce', price: 2.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Main Course'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item8-${restaurantId}`, name: 'Dal Makhani', description: 'Creamy black lentils with butter', price: 1.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Main Course'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item9-${restaurantId}`, name: 'Chicken Curry', description: 'Traditional chicken curry', price: 2.79, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Main Course'), spicyLevel: 2 },
        { _id: `item10-${restaurantId}`, name: 'Rajma', description: 'Red kidney beans in spiced gravy', price: 1.79, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Main Course'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item33-${restaurantId}`, name: 'Aloo Gobi', description: 'Cauliflower and potato curry', price: 1.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item33', 'Main Course'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item34-${restaurantId}`, name: 'Chole', description: 'Spiced chickpea curry', price: 1.79, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item34', 'Main Course'), isVegetarian: true, spicyLevel: 2 },
        { _id: `item35-${restaurantId}`, name: 'Paneer Makhani', description: 'Cottage cheese in rich tomato gravy', price: 2.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item35', 'Main Course'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item11-${restaurantId}`, name: 'Naan', description: 'Traditional tandoor bread', price: 0.59, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Breads'), isVegetarian: true },
        { _id: `item12-${restaurantId}`, name: 'Garlic Naan', description: 'Naan with garlic and butter', price: 0.79, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Breads'), isVegetarian: true },
        { _id: `item13-${restaurantId}`, name: 'Roti', description: 'Whole wheat flatbread', price: 0.39, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Breads'), isVegetarian: true },
        { _id: `item14-${restaurantId}`, name: 'Paratha', description: 'Layered flatbread with ghee', price: 0.79, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Breads'), isVegetarian: true },
        { _id: `item15-${restaurantId}`, name: 'Kulcha', description: 'Stuffed bread with onions', price: 0.99, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Breads'), isVegetarian: true },
        { _id: `item38-${restaurantId}`, name: 'Butter Naan', description: 'Naan brushed with butter', price: 0.69, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item38', 'Breads'), isVegetarian: true },
        { _id: `item39-${restaurantId}`, name: 'Cheese Naan', description: 'Naan stuffed with cheese', price: 1.29, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item39', 'Breads'), isVegetarian: true },
        { _id: `item40-${restaurantId}`, name: 'Aloo Paratha', description: 'Potato-stuffed flatbread', price: 1.19, category: 'Breads', image: getUniqueMenuItemImage(restaurantId, 'item40', 'Breads'), isVegetarian: true },
        { _id: `item16-${restaurantId}`, name: 'Chicken Biryani', description: 'Fragrant rice with chicken and spices', price: 3.49, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Rice'), spicyLevel: 2 },
        { _id: `item17-${restaurantId}`, name: 'Vegetable Biryani', description: 'Aromatic rice with mixed vegetables', price: 2.79, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Rice'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item18-${restaurantId}`, name: 'Jeera Rice', description: 'Basmati rice with cumin seeds', price: 1.49, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Rice'), isVegetarian: true },
        { _id: `item19-${restaurantId}`, name: 'Plain Rice', description: 'Steamed basmati rice', price: 0.99, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Rice'), isVegetarian: true },
        { _id: `item20-${restaurantId}`, name: 'Pulao', description: 'Spiced rice with vegetables', price: 2.29, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Rice'), isVegetarian: true },
        { _id: `item36-${restaurantId}`, name: 'Mutton Biryani', description: 'Aromatic rice with tender mutton', price: 3.99, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item36', 'Rice'), spicyLevel: 2 },
        { _id: `item37-${restaurantId}`, name: 'Egg Biryani', description: 'Spiced rice with boiled eggs', price: 2.99, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item37', 'Rice'), spicyLevel: 1 },
        { _id: `item21-${restaurantId}`, name: 'Gulab Jamun (2 pcs)', description: 'Sweet milk solids in sugar syrup', price: 0.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Desserts'), isVegetarian: true },
        { _id: `item22-${restaurantId}`, name: 'Rasmalai (2 pcs)', description: 'Cottage cheese in sweetened milk', price: 1.29, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Desserts'), isVegetarian: true },
        { _id: `item23-${restaurantId}`, name: 'Kheer', description: 'Rice pudding with cardamom', price: 0.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Desserts'), isVegetarian: true },
        { _id: `item24-${restaurantId}`, name: 'Kulfi', description: 'Traditional Indian ice cream', price: 0.79, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Desserts'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Jalebi', description: 'Crispy sweet spirals in syrup', price: 1.19, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Desserts'), isVegetarian: true },
        { _id: `item43-${restaurantId}`, name: 'Rasgulla (3 pcs)', description: 'Spongy cottage cheese balls in syrup', price: 0.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item43', 'Desserts'), isVegetarian: true },
        { _id: `item44-${restaurantId}`, name: 'Gajar Halwa', description: 'Carrot pudding with nuts', price: 1.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item44', 'Desserts'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Masala Chai', description: 'Spiced Indian tea with milk', price: 0.59, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Beverages'), isVegetarian: true },
        { _id: `item27-${restaurantId}`, name: 'Lassi', description: 'Yogurt-based drink', price: 0.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Beverages'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'Fresh Lime Water', description: 'Lime juice with water and mint', price: 0.59, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Beverages'), isVegetarian: true },
        { _id: `item29-${restaurantId}`, name: 'Mango Juice', description: 'Fresh mango juice', price: 1.29, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item29', 'Beverages'), isVegetarian: true },
        { _id: `item30-${restaurantId}`, name: 'Buttermilk', description: 'Spiced yogurt drink', price: 0.79, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item30', 'Beverages'), isVegetarian: true },
        { _id: `item41-${restaurantId}`, name: 'Mango Lassi', description: 'Sweet mango yogurt drink', price: 1.19, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item41', 'Beverages'), isVegetarian: true },
        { _id: `item42-${restaurantId}`, name: 'Rose Milk', description: 'Milk flavored with rose syrup', price: 0.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item42', 'Beverages'), isVegetarian: true },
        { _id: `item45-${restaurantId}`, name: 'Tandoori Chicken', description: 'Marinated chicken cooked in tandoor', price: 3.49, category: 'Tandoor', image: getUniqueMenuItemImage(restaurantId, 'item45', 'Tandoor'), spicyLevel: 2 },
        { _id: `item46-${restaurantId}`, name: 'Seekh Kebab', description: 'Spiced minced meat skewers', price: 2.99, category: 'Tandoor', image: getUniqueMenuItemImage(restaurantId, 'item46', 'Tandoor'), spicyLevel: 2 },
        { _id: `item47-${restaurantId}`, name: 'Tandoori Prawns', description: 'Marinated prawns in tandoor', price: 3.99, category: 'Tandoor', image: getUniqueMenuItemImage(restaurantId, 'item47', 'Tandoor'), spicyLevel: 2 },
        { _id: `item48-${restaurantId}`, name: 'Pani Puri', description: 'Crispy shells with spiced water', price: 1.49, category: 'Street Food', image: getUniqueMenuItemImage(restaurantId, 'item48', 'Street Food'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item49-${restaurantId}`, name: 'Bhel Puri', description: 'Puffed rice with chutneys', price: 1.29, category: 'Street Food', image: getUniqueMenuItemImage(restaurantId, 'item49', 'Street Food'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item50-${restaurantId}`, name: 'Vada Pav', description: 'Spiced potato fritter in bun', price: 0.99, category: 'Street Food', image: getUniqueMenuItemImage(restaurantId, 'item50', 'Street Food'), isVegetarian: true, spicyLevel: 2 },
        { _id: `item51-${restaurantId}`, name: 'Pav Bhaji', description: 'Spiced vegetable curry with bread', price: 1.99, category: 'Street Food', image: getUniqueMenuItemImage(restaurantId, 'item51', 'Street Food'), isVegetarian: true, spicyLevel: 2 },
        { _id: `item52-${restaurantId}`, name: 'Dosa Varieties', description: 'Crispy crepes with different fillings', price: 1.79, category: 'Street Food', image: getUniqueMenuItemImage(restaurantId, 'item52', 'Street Food'), isVegetarian: true }
      ]
    },
    
    asian: {
      _id: `menu-${restaurantId}`,
      name: 'Asian Menu',
      categories: ['Appetizers', 'Sushi', 'Sashimi', 'Noodles', 'Main Course', 'Rice', 'Dim Sum', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Gyoza (6 pcs)', description: 'Pan-fried pork dumplings', price: 3.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Appetizers') },
        { _id: `item2-${restaurantId}`, name: 'Spring Rolls (4 pcs)', description: 'Crispy vegetable spring rolls', price: 2.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Appetizers'), isVegetarian: true },
        { _id: `item3-${restaurantId}`, name: 'Chicken Satay (4 pcs)', description: 'Grilled chicken with peanut sauce', price: 4.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Appetizers') },
        { _id: `item4-${restaurantId}`, name: 'Edamame', description: 'Steamed soybeans with sea salt', price: 2.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Appetizers'), isVegetarian: true },
        { _id: `item5-${restaurantId}`, name: 'Tempura Vegetables', description: 'Lightly battered and fried vegetables', price: 4.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Appetizers'), isVegetarian: true },
        { _id: `item6-${restaurantId}`, name: 'Salmon Nigiri (2 pcs)', description: 'Fresh salmon over sushi rice', price: 3.99, category: 'Sushi', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Sushi') },
        { _id: `item7-${restaurantId}`, name: 'California Roll (8 pcs)', description: 'Crab, avocado, and cucumber roll', price: 4.99, category: 'Sushi', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Sushi') },
        { _id: `item8-${restaurantId}`, name: 'Spicy Tuna Roll (8 pcs)', description: 'Spicy tuna and cucumber roll', price: 5.49, category: 'Sushi', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Sushi'), spicyLevel: 2 },
        { _id: `item9-${restaurantId}`, name: 'Vegetable Roll (8 pcs)', description: 'Fresh vegetables in sushi rice', price: 3.99, category: 'Sushi', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Sushi'), isVegetarian: true },
        { _id: `item10-${restaurantId}`, name: 'Dragon Roll (8 pcs)', description: 'Eel and cucumber with avocado', price: 6.99, category: 'Sushi', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Sushi') },
        { _id: `item11-${restaurantId}`, name: 'Tonkotsu Ramen', description: 'Rich pork bone broth with noodles', price: 7.99, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Noodles') },
        { _id: `item12-${restaurantId}`, name: 'Pad Thai', description: 'Stir-fried rice noodles with peanuts', price: 6.99, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Noodles'), spicyLevel: 1 },
        { _id: `item13-${restaurantId}`, name: 'Vegetable Lo Mein', description: 'Stir-fried noodles with vegetables', price: 5.99, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Noodles'), isVegetarian: true },
        { _id: `item14-${restaurantId}`, name: 'Udon Soup', description: 'Thick wheat noodles in broth', price: 6.49, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Noodles'), isVegetarian: true },
        { _id: `item15-${restaurantId}`, name: 'Pho', description: 'Vietnamese noodle soup with beef', price: 7.49, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Noodles') },
        { _id: `item16-${restaurantId}`, name: 'Kung Pao Chicken', description: 'Stir-fried chicken with peanuts', price: 7.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Main Course'), spicyLevel: 3 },
        { _id: `item17-${restaurantId}`, name: 'Beef Bulgogi', description: 'Korean marinated beef', price: 8.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Main Course') },
        { _id: `item18-${restaurantId}`, name: 'Sweet and Sour Pork', description: 'Crispy pork in tangy sauce', price: 7.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Main Course') },
        { _id: `item19-${restaurantId}`, name: 'Teriyaki Chicken', description: 'Grilled chicken with teriyaki glaze', price: 7.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Main Course') },
        { _id: `item20-${restaurantId}`, name: 'Mapo Tofu', description: 'Spicy tofu in Sichuan sauce', price: 6.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Main Course'), isVegetarian: true, spicyLevel: 3 },
        { _id: `item21-${restaurantId}`, name: 'Chicken Fried Rice', description: 'Wok-fried rice with chicken', price: 6.49, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Rice') },
        { _id: `item22-${restaurantId}`, name: 'Vegetable Fried Rice', description: 'Wok-fried rice with vegetables', price: 5.49, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Rice'), isVegetarian: true },
        { _id: `item23-${restaurantId}`, name: 'Bibimbap', description: 'Korean mixed rice bowl', price: 6.99, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Rice'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item24-${restaurantId}`, name: 'Steamed Rice', description: 'Plain steamed jasmine rice', price: 2.99, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Rice'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Coconut Rice', description: 'Rice cooked in coconut milk', price: 4.49, category: 'Rice', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Rice'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Matcha Ice Cream', description: 'Green tea flavored ice cream', price: 2.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Desserts'), isVegetarian: true },
        { _id: `item27-${restaurantId}`, name: 'Mochi Ice Cream (3 pcs)', description: 'Rice cake filled with ice cream', price: 2.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Desserts'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'Mango Sticky Rice', description: 'Sweet rice with fresh mango', price: 3.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Desserts'), isVegetarian: true },
        { _id: `item29-${restaurantId}`, name: 'Red Bean Ice Cream', description: 'Traditional Asian dessert', price: 2.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item29', 'Desserts'), isVegetarian: true },
        { _id: `item30-${restaurantId}`, name: 'Sesame Balls', description: 'Fried glutinous rice balls', price: 3.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item30', 'Desserts'), isVegetarian: true },
        { _id: `item31-${restaurantId}`, name: 'Green Tea', description: 'Traditional hot green tea', price: 1.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item31', 'Beverages'), isVegetarian: true },
        { _id: `item32-${restaurantId}`, name: 'Thai Iced Tea', description: 'Sweet and creamy Thai tea', price: 2.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item32', 'Beverages'), isVegetarian: true },
        { _id: `item33-${restaurantId}`, name: 'Fresh Coconut Water', description: 'Natural coconut water', price: 2.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item33', 'Beverages'), isVegetarian: true },
        { _id: `item34-${restaurantId}`, name: 'Lychee Juice', description: 'Sweet lychee fruit juice', price: 2.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item34', 'Beverages'), isVegetarian: true },
        { _id: `item35-${restaurantId}`, name: 'Hot Sake', description: 'Traditional Japanese rice wine', price: 3.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item35', 'Beverages'), isVegetarian: true },
        { _id: `item36-${restaurantId}`, name: 'Tuna Sashimi', description: 'Fresh raw tuna slices', price: 4.99, category: 'Sashimi', image: getUniqueMenuItemImage(restaurantId, 'item36', 'Sashimi') },
        { _id: `item37-${restaurantId}`, name: 'Salmon Sashimi', description: 'Fresh raw salmon slices', price: 4.49, category: 'Sashimi', image: getUniqueMenuItemImage(restaurantId, 'item37', 'Sashimi') },
        { _id: `item38-${restaurantId}`, name: 'Mixed Sashimi', description: 'Assorted fresh fish selection', price: 6.99, category: 'Sashimi', image: getUniqueMenuItemImage(restaurantId, 'item38', 'Sashimi') },
        { _id: `item39-${restaurantId}`, name: 'Har Gow', description: 'Steamed shrimp dumplings', price: 3.99, category: 'Dim Sum', image: getUniqueMenuItemImage(restaurantId, 'item39', 'Dim Sum') },
        { _id: `item40-${restaurantId}`, name: 'Siu Mai', description: 'Steamed pork and shrimp dumplings', price: 3.79, category: 'Dim Sum', image: getUniqueMenuItemImage(restaurantId, 'item40', 'Dim Sum') },
        { _id: `item41-${restaurantId}`, name: 'Char Siu Bao', description: 'BBQ pork steamed buns', price: 4.29, category: 'Dim Sum', image: getUniqueMenuItemImage(restaurantId, 'item41', 'Dim Sum') },
        { _id: `item42-${restaurantId}`, name: 'Xiaolongbao', description: 'Soup dumplings with pork', price: 4.99, category: 'Dim Sum', image: getUniqueMenuItemImage(restaurantId, 'item42', 'Dim Sum') }
      ]
    },
    
    brewery: {
      _id: `menu-${restaurantId}`,
      name: 'Brewery Menu',
      categories: ['Craft Beers', 'Appetizers', 'Burgers', 'Main Course', 'Sides', 'Desserts', 'Non-Alcoholic'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'House IPA', description: 'Hoppy India Pale Ale', price: 4.99, category: 'Craft Beers', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Craft Beers') },
        { _id: `item2-${restaurantId}`, name: 'Wheat Beer', description: 'Belgian-style wheat beer', price: 4.49, category: 'Craft Beers', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Craft Beers') },
        { _id: `item3-${restaurantId}`, name: 'Stout', description: 'Rich dark beer with coffee notes', price: 5.49, category: 'Craft Beers', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Craft Beers') },
        { _id: `item4-${restaurantId}`, name: 'Lager', description: 'Crisp and refreshing lager', price: 3.99, category: 'Craft Beers', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Craft Beers') },
        { _id: `item5-${restaurantId}`, name: 'Pale Ale', description: 'Balanced hoppy pale ale', price: 4.49, category: 'Craft Beers', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Craft Beers') },
        { _id: `item6-${restaurantId}`, name: 'Loaded Nachos', description: 'Tortilla chips with cheese and jalapeños', price: 5.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Appetizers'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item7-${restaurantId}`, name: 'Buffalo Wings (8 pcs)', description: 'Spicy chicken wings', price: 6.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Appetizers'), spicyLevel: 2 },
        { _id: `item8-${restaurantId}`, name: 'Onion Rings', description: 'Beer-battered onion rings', price: 4.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Appetizers'), isVegetarian: true },
        { _id: `item9-${restaurantId}`, name: 'Mozzarella Sticks', description: 'Fried mozzarella with marinara', price: 5.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Appetizers'), isVegetarian: true },
        { _id: `item10-${restaurantId}`, name: 'Potato Skins', description: 'Loaded potato skins with bacon', price: 5.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Appetizers') },
        { _id: `item11-${restaurantId}`, name: 'Classic Burger', description: 'Beef patty with lettuce and tomato', price: 7.99, category: 'Burgers', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Burgers') },
        { _id: `item12-${restaurantId}`, name: 'Cheeseburger', description: 'Beef patty with cheese', price: 8.49, category: 'Burgers', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Burgers') },
        { _id: `item13-${restaurantId}`, name: 'BBQ Burger', description: 'Burger with BBQ sauce and onions', price: 8.99, category: 'Burgers', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Burgers') },
        { _id: `item14-${restaurantId}`, name: 'Veggie Burger', description: 'Plant-based patty with vegetables', price: 7.49, category: 'Burgers', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Burgers'), isVegetarian: true },
        { _id: `item15-${restaurantId}`, name: 'Bacon Burger', description: 'Beef patty with crispy bacon', price: 9.49, category: 'Burgers', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Burgers') },
        { _id: `item16-${restaurantId}`, name: 'Fish and Chips', description: 'Beer-battered fish with fries', price: 8.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Main Course') },
        { _id: `item17-${restaurantId}`, name: 'Grilled Steak', description: 'Juicy grilled steak with herbs', price: 12.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Main Course') },
        { _id: `item18-${restaurantId}`, name: 'BBQ Ribs', description: 'Slow-cooked ribs with BBQ sauce', price: 11.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Main Course') },
        { _id: `item19-${restaurantId}`, name: 'Grilled Chicken', description: 'Herb-marinated grilled chicken', price: 9.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Main Course') },
        { _id: `item20-${restaurantId}`, name: 'Pulled Pork Sandwich', description: 'Slow-cooked pulled pork', price: 8.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Main Course') },
        { _id: `item21-${restaurantId}`, name: 'French Fries', description: 'Crispy golden fries', price: 2.99, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Sides'), isVegetarian: true },
        { _id: `item22-${restaurantId}`, name: 'Sweet Potato Fries', description: 'Crispy sweet potato fries', price: 3.49, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Sides'), isVegetarian: true },
        { _id: `item23-${restaurantId}`, name: 'Coleslaw', description: 'Fresh cabbage and carrot salad', price: 2.49, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Sides'), isVegetarian: true },
        { _id: `item24-${restaurantId}`, name: 'Mac and Cheese', description: 'Creamy macaroni and cheese', price: 4.99, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Sides'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Garden Salad', description: 'Mixed greens with vinaigrette', price: 3.99, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Sides'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Chocolate Brownie', description: 'Warm brownie with ice cream', price: 3.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Desserts'), isVegetarian: true },
        { _id: `item27-${restaurantId}`, name: 'Apple Pie', description: 'Classic apple pie with cinnamon', price: 3.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Desserts'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'Cheesecake', description: 'New York style cheesecake', price: 3.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Desserts'), isVegetarian: true },
        { _id: `item29-${restaurantId}`, name: 'Ice Cream Sundae', description: 'Vanilla ice cream with toppings', price: 2.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item29', 'Desserts'), isVegetarian: true },
        { _id: `item30-${restaurantId}`, name: 'Cookies', description: 'Freshly baked chocolate chip cookies', price: 2.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item30', 'Desserts'), isVegetarian: true },
        { _id: `item31-${restaurantId}`, name: 'Soft Drinks', description: 'Assorted sodas', price: 1.99, category: 'Non-Alcoholic', image: getUniqueMenuItemImage(restaurantId, 'item31', 'Non-Alcoholic'), isVegetarian: true },
        { _id: `item32-${restaurantId}`, name: 'Fresh Juice', description: 'Seasonal fruit juice', price: 2.99, category: 'Non-Alcoholic', image: getUniqueMenuItemImage(restaurantId, 'item32', 'Non-Alcoholic'), isVegetarian: true },
        { _id: `item33-${restaurantId}`, name: 'Coffee', description: 'Freshly brewed coffee', price: 2.49, category: 'Non-Alcoholic', image: getUniqueMenuItemImage(restaurantId, 'item33', 'Non-Alcoholic'), isVegetarian: true },
        { _id: `item34-${restaurantId}`, name: 'Iced Tea', description: 'Refreshing iced tea', price: 1.99, category: 'Non-Alcoholic', image: getUniqueMenuItemImage(restaurantId, 'item34', 'Non-Alcoholic'), isVegetarian: true },
        { _id: `item35-${restaurantId}`, name: 'Lemonade', description: 'Fresh squeezed lemonade', price: 2.49, category: 'Non-Alcoholic', image: getUniqueMenuItemImage(restaurantId, 'item35', 'Non-Alcoholic'), isVegetarian: true }
      ]
    },
    
    seafood: {
      _id: `menu-${restaurantId}`,
      name: 'Seafood Menu',
      categories: ['Fresh Catch', 'Shellfish', 'Grilled', 'Fried', 'Soups', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Grilled Salmon', description: 'Fresh Atlantic salmon with herbs', price: 12.99, category: 'Fresh Catch', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Fresh Catch') },
        { _id: `item2-${restaurantId}`, name: 'Pan-Seared Tuna', description: 'Seared tuna with sesame crust', price: 14.99, category: 'Fresh Catch', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Fresh Catch') },
        { _id: `item3-${restaurantId}`, name: 'Cod Fish & Chips', description: 'Beer-battered cod with fries', price: 10.99, category: 'Fresh Catch', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Fresh Catch') },
        { _id: `item4-${restaurantId}`, name: 'Mahi-Mahi Tacos', description: 'Grilled mahi-mahi with tropical salsa', price: 9.99, category: 'Fresh Catch', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Fresh Catch') },
        { _id: `item5-${restaurantId}`, name: 'Halibut Steak', description: 'Grilled halibut with lemon butter', price: 16.99, category: 'Fresh Catch', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Fresh Catch') },
        { _id: `item6-${restaurantId}`, name: 'Lobster Tail', description: 'Steamed lobster tail with garlic butter', price: 24.99, category: 'Shellfish', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Shellfish') },
        { _id: `item7-${restaurantId}`, name: 'King Crab Legs', description: 'Alaskan king crab legs', price: 28.99, category: 'Shellfish', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Shellfish') },
        { _id: `item8-${restaurantId}`, name: 'Shrimp Scampi', description: 'Garlic butter shrimp over pasta', price: 13.99, category: 'Shellfish', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Shellfish') },
        { _id: `item9-${restaurantId}`, name: 'Mussels Marinara', description: 'Fresh mussels in tomato sauce', price: 11.99, category: 'Shellfish', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Shellfish') },
        { _id: `item10-${restaurantId}`, name: 'Oysters Rockefeller', description: 'Baked oysters with spinach', price: 15.99, category: 'Shellfish', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Shellfish') },
        { _id: `item11-${restaurantId}`, name: 'Grilled Octopus', description: 'Mediterranean-style grilled octopus', price: 14.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Grilled') },
        { _id: `item12-${restaurantId}`, name: 'BBQ Shrimp', description: 'Grilled shrimp with BBQ glaze', price: 12.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Grilled') },
        { _id: `item13-${restaurantId}`, name: 'Grilled Swordfish', description: 'Marinated swordfish steak', price: 15.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Grilled') },
        { _id: `item14-${restaurantId}`, name: 'Cedar Plank Salmon', description: 'Salmon cooked on cedar plank', price: 16.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Grilled') },
        { _id: `item15-${restaurantId}`, name: 'Grilled Sea Bass', description: 'Whole grilled sea bass', price: 18.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Grilled') },
        { _id: `item16-${restaurantId}`, name: 'Fried Calamari', description: 'Crispy squid rings with marinara', price: 8.99, category: 'Fried', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Fried') },
        { _id: `item17-${restaurantId}`, name: 'Fish & Chips', description: 'Classic beer-battered fish', price: 11.99, category: 'Fried', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Fried') },
        { _id: `item18-${restaurantId}`, name: 'Coconut Shrimp', description: 'Breaded shrimp with coconut', price: 10.99, category: 'Fried', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Fried') },
        { _id: `item19-${restaurantId}`, name: 'Fried Oysters', description: 'Cornmeal-crusted oysters', price: 12.99, category: 'Fried', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Fried') },
        { _id: `item20-${restaurantId}`, name: 'Tempura Prawns', description: 'Light tempura battered prawns', price: 13.99, category: 'Fried', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Fried') },
        { _id: `item21-${restaurantId}`, name: 'Clam Chowder', description: 'New England style clam chowder', price: 5.99, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Soups') },
        { _id: `item22-${restaurantId}`, name: 'Seafood Bisque', description: 'Rich lobster and crab bisque', price: 7.99, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Soups') },
        { _id: `item23-${restaurantId}`, name: 'Fish Soup', description: 'Mediterranean fish soup', price: 6.99, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Soups') },
        { _id: `item24-${restaurantId}`, name: 'Key Lime Pie', description: 'Traditional Florida key lime pie', price: 4.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Desserts'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Coconut Cake', description: 'Tropical coconut layer cake', price: 4.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Desserts'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Fresh Lemonade', description: 'House-made fresh lemonade', price: 2.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Beverages'), isVegetarian: true },
        { _id: `item27-${restaurantId}`, name: 'Iced Tea', description: 'Sweet or unsweetened tea', price: 2.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Beverages'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'White Wine', description: 'Crisp white wine selection', price: 6.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Beverages'), isVegetarian: true }
      ]
    },
    
    continental: {
      _id: `menu-${restaurantId}`,
      name: 'Continental Menu',
      categories: ['Appetizers', 'Soups & Salads', 'Main Course', 'Steaks', 'Pasta', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Cheese Platter', description: 'Selection of European cheeses', price: 8.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Appetizers'), isVegetarian: true },
        { _id: `item2-${restaurantId}`, name: 'Stuffed Mushrooms', description: 'Mushrooms stuffed with herbs and cheese', price: 6.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Appetizers'), isVegetarian: true },
        { _id: `item3-${restaurantId}`, name: 'Chicken Liver Pâté', description: 'Smooth pâté with toast points', price: 7.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Appetizers') },
        { _id: `item4-${restaurantId}`, name: 'Escargot', description: 'French snails in garlic butter', price: 9.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Appetizers') },
        { _id: `item5-${restaurantId}`, name: 'Prosciutto & Melon', description: 'Italian cured ham with cantaloupe', price: 8.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Appetizers') },
        { _id: `item6-${restaurantId}`, name: 'French Onion Soup', description: 'Classic soup with Gruyère cheese', price: 5.99, category: 'Soups & Salads', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Soups & Salads'), isVegetarian: true },
        { _id: `item7-${restaurantId}`, name: 'Caesar Salad', description: 'Romaine with parmesan and croutons', price: 6.99, category: 'Soups & Salads', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Soups & Salads'), isVegetarian: true },
        { _id: `item8-${restaurantId}`, name: 'Waldorf Salad', description: 'Apples, celery, walnuts, and mayo', price: 6.49, category: 'Soups & Salads', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Soups & Salads'), isVegetarian: true },
        { _id: `item9-${restaurantId}`, name: 'Mushroom Soup', description: 'Creamy wild mushroom soup', price: 5.49, category: 'Soups & Salads', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Soups & Salads'), isVegetarian: true },
        { _id: `item10-${restaurantId}`, name: 'Mixed Green Salad', description: 'Fresh greens with vinaigrette', price: 5.99, category: 'Soups & Salads', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Soups & Salads'), isVegetarian: true },
        { _id: `item11-${restaurantId}`, name: 'Coq au Vin', description: 'Chicken braised in red wine', price: 14.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Main Course') },
        { _id: `item12-${restaurantId}`, name: 'Duck à l\'Orange', description: 'Roasted duck with orange sauce', price: 18.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Main Course') },
        { _id: `item13-${restaurantId}`, name: 'Beef Wellington', description: 'Beef tenderloin in puff pastry', price: 22.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Main Course') },
        { _id: `item14-${restaurantId}`, name: 'Lamb Rack', description: 'Herb-crusted rack of lamb', price: 19.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Main Course') },
        { _id: `item15-${restaurantId}`, name: 'Chicken Cordon Bleu', description: 'Stuffed chicken with ham and cheese', price: 15.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Main Course') },
        { _id: `item16-${restaurantId}`, name: 'Filet Mignon', description: 'Tender beef filet with red wine sauce', price: 24.99, category: 'Steaks', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Steaks') },
        { _id: `item17-${restaurantId}`, name: 'Ribeye Steak', description: 'Juicy ribeye with herb butter', price: 21.99, category: 'Steaks', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Steaks') },
        { _id: `item18-${restaurantId}`, name: 'New York Strip', description: 'Classic NY strip steak', price: 20.99, category: 'Steaks', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Steaks') },
        { _id: `item19-${restaurantId}`, name: 'T-Bone Steak', description: 'Large T-bone with sides', price: 23.99, category: 'Steaks', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Steaks') },
        { _id: `item20-${restaurantId}`, name: 'Porterhouse', description: 'Premium porterhouse steak', price: 26.99, category: 'Steaks', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Steaks') },
        { _id: `item21-${restaurantId}`, name: 'Linguine Alfredo', description: 'Creamy parmesan pasta', price: 11.99, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Pasta'), isVegetarian: true },
        { _id: `item22-${restaurantId}`, name: 'Beef Stroganoff', description: 'Tender beef in cream sauce', price: 13.99, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Pasta') },
        { _id: `item23-${restaurantId}`, name: 'Chicken Piccata', description: 'Chicken in lemon caper sauce', price: 12.99, category: 'Pasta', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Pasta') },
        { _id: `item24-${restaurantId}`, name: 'Crème Brûlée', description: 'Classic French custard dessert', price: 5.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Desserts'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Chocolate Mousse', description: 'Rich chocolate mousse', price: 4.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Desserts'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Wine Selection', description: 'Curated wine list', price: 8.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Beverages'), isVegetarian: true },
        { _id: `item27-${restaurantId}`, name: 'Cocktails', description: 'Classic cocktail menu', price: 9.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Beverages'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'Coffee', description: 'Freshly brewed coffee', price: 2.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Beverages'), isVegetarian: true }
      ]
    },
    
    middle_eastern: {
      _id: `menu-${restaurantId}`,
      name: 'Middle Eastern Menu',
      categories: ['Appetizers', 'Grilled', 'Rice & Bread', 'Vegetarian', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Hummus', description: 'Chickpea dip with tahini and olive oil', price: 3.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Appetizers'), isVegetarian: true },
        { _id: `item2-${restaurantId}`, name: 'Baba Ganoush', description: 'Roasted eggplant dip with garlic', price: 4.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Appetizers'), isVegetarian: true },
        { _id: `item3-${restaurantId}`, name: 'Falafel (6 pcs)', description: 'Deep-fried chickpea balls', price: 4.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Appetizers'), isVegetarian: true },
        { _id: `item4-${restaurantId}`, name: 'Tabbouleh', description: 'Parsley salad with tomatoes and bulgur', price: 3.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Appetizers'), isVegetarian: true },
        { _id: `item5-${restaurantId}`, name: 'Stuffed Grape Leaves', description: 'Rice-stuffed vine leaves', price: 5.49, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Appetizers'), isVegetarian: true },
        { _id: `item6-${restaurantId}`, name: 'Lamb Kebab', description: 'Grilled lamb skewers with spices', price: 12.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Grilled'), spicyLevel: 1 },
        { _id: `item7-${restaurantId}`, name: 'Chicken Shawarma', description: 'Marinated chicken with garlic sauce', price: 9.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Grilled') },
        { _id: `item8-${restaurantId}`, name: 'Mixed Grill Platter', description: 'Assorted grilled meats', price: 16.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Grilled') },
        { _id: `item9-${restaurantId}`, name: 'Beef Kofta', description: 'Spiced ground beef skewers', price: 11.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Grilled'), spicyLevel: 1 },
        { _id: `item10-${restaurantId}`, name: 'Grilled Fish', description: 'Mediterranean-style grilled fish', price: 13.99, category: 'Grilled', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Grilled') },
        { _id: `item11-${restaurantId}`, name: 'Persian Rice', description: 'Saffron rice with barberries', price: 4.99, category: 'Rice & Bread', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Rice & Bread'), isVegetarian: true },
        { _id: `item12-${restaurantId}`, name: 'Pita Bread', description: 'Fresh baked pita bread', price: 1.99, category: 'Rice & Bread', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Rice & Bread'), isVegetarian: true },
        { _id: `item13-${restaurantId}`, name: 'Naan Bread', description: 'Traditional Persian bread', price: 2.49, category: 'Rice & Bread', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Rice & Bread'), isVegetarian: true },
        { _id: `item14-${restaurantId}`, name: 'Jeweled Rice', description: 'Rice with dried fruits and nuts', price: 5.99, category: 'Rice & Bread', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Rice & Bread'), isVegetarian: true },
        { _id: `item15-${restaurantId}`, name: 'Lavash', description: 'Thin flatbread', price: 1.49, category: 'Rice & Bread', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Rice & Bread'), isVegetarian: true },
        { _id: `item16-${restaurantId}`, name: 'Vegetarian Platter', description: 'Mixed vegetarian dishes', price: 8.99, category: 'Vegetarian', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Vegetarian'), isVegetarian: true },
        { _id: `item17-${restaurantId}`, name: 'Stuffed Eggplant', description: 'Eggplant stuffed with rice and herbs', price: 7.99, category: 'Vegetarian', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Vegetarian'), isVegetarian: true },
        { _id: `item18-${restaurantId}`, name: 'Lentil Stew', description: 'Persian lentil and herb stew', price: 6.99, category: 'Vegetarian', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Vegetarian'), isVegetarian: true },
        { _id: `item19-${restaurantId}`, name: 'Baklava', description: 'Honey-sweetened pastry with nuts', price: 3.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Desserts'), isVegetarian: true },
        { _id: `item20-${restaurantId}`, name: 'Persian Ice Cream', description: 'Rosewater and pistachio ice cream', price: 2.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Desserts'), isVegetarian: true },
        { _id: `item21-${restaurantId}`, name: 'Mint Tea', description: 'Traditional Middle Eastern tea', price: 1.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Beverages'), isVegetarian: true },
        { _id: `item22-${restaurantId}`, name: 'Turkish Coffee', description: 'Strong traditional coffee', price: 2.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Beverages'), isVegetarian: true },
        { _id: `item23-${restaurantId}`, name: 'Fresh Pomegranate Juice', description: 'Pure pomegranate juice', price: 3.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Beverages'), isVegetarian: true }
      ]
    },
    
    fine_dining: {
      _id: `menu-${restaurantId}`,
      name: 'Fine Dining Menu',
      categories: ['Amuse-Bouche', 'Appetizers', 'Soups', 'Main Course', 'Desserts', 'Wine & Cocktails'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Caviar Service', description: 'Premium caviar with traditional accompaniments', price: 45.99, category: 'Amuse-Bouche', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Amuse-Bouche') },
        { _id: `item2-${restaurantId}`, name: 'Oyster Trio', description: 'Three varieties of fresh oysters', price: 18.99, category: 'Amuse-Bouche', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Amuse-Bouche') },
        { _id: `item3-${restaurantId}`, name: 'Foie Gras', description: 'Pan-seared foie gras with fig compote', price: 28.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Appetizers') },
        { _id: `item4-${restaurantId}`, name: 'Lobster Bisque', description: 'Rich lobster soup with cognac', price: 16.99, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Soups') },
        { _id: `item5-${restaurantId}`, name: 'Wagyu Beef', description: 'Premium wagyu steak with truffle sauce', price: 65.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Main Course') },
        { _id: `item6-${restaurantId}`, name: 'Chocolate Soufflé', description: 'Warm chocolate soufflé with vanilla ice cream', price: 12.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Desserts'), isVegetarian: true },
        { _id: `item7-${restaurantId}`, name: 'Champagne', description: 'Premium champagne selection', price: 25.99, category: 'Wine & Cocktails', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Wine & Cocktails'), isVegetarian: true }
      ]
    },
    
    thai_vietnamese: {
      _id: `menu-${restaurantId}`,
      name: 'Thai & Vietnamese Menu',
      categories: ['Appetizers', 'Soups', 'Noodles', 'Curries', 'Stir-Fry', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'Fresh Spring Rolls (2 pcs)', description: 'Rice paper rolls with fresh herbs', price: 4.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Appetizers'), isVegetarian: true },
        { _id: `item2-${restaurantId}`, name: 'Satay Chicken (4 pcs)', description: 'Grilled chicken with peanut sauce', price: 6.99, category: 'Appetizers', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Appetizers') },
        { _id: `item3-${restaurantId}`, name: 'Tom Yum Soup', description: 'Spicy and sour Thai soup', price: 5.99, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Soups'), spicyLevel: 2 },
        { _id: `item4-${restaurantId}`, name: 'Pho Bo', description: 'Vietnamese beef noodle soup', price: 8.99, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Noodles') },
        { _id: `item5-${restaurantId}`, name: 'Pad Thai', description: 'Stir-fried rice noodles with tamarind', price: 7.99, category: 'Noodles', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Noodles'), spicyLevel: 1 },
        { _id: `item6-${restaurantId}`, name: 'Green Curry', description: 'Thai green curry with coconut milk', price: 9.99, category: 'Curries', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Curries'), spicyLevel: 3 },
        { _id: `item7-${restaurantId}`, name: 'Basil Stir-Fry', description: 'Thai basil stir-fry with chili', price: 8.49, category: 'Stir-Fry', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Stir-Fry'), spicyLevel: 2 },
        { _id: `item8-${restaurantId}`, name: 'Mango Sticky Rice', description: 'Sweet coconut rice with mango', price: 4.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Desserts'), isVegetarian: true },
        { _id: `item9-${restaurantId}`, name: 'Thai Iced Tea', description: 'Sweet and creamy Thai tea', price: 2.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Beverages'), isVegetarian: true }
      ]
    },
    
    default: {
      _id: `menu-${restaurantId}`,
      name: 'Main Menu',
      categories: ['Starters', 'Soups', 'Main Course', 'Grilled Items', 'Sides', 'Desserts', 'Beverages'],
      items: [
        { _id: `item1-${restaurantId}`, name: 'House Special Appetizer', description: 'Chef special appetizer', price: 1.99, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item1', 'Starters') },
        { _id: `item2-${restaurantId}`, name: 'Vegetable Spring Rolls', description: 'Crispy spring rolls', price: 1.29, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item2', 'Starters'), isVegetarian: true },
        { _id: `item3-${restaurantId}`, name: 'Chicken Wings', description: 'Crispy chicken wings', price: 1.99, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item3', 'Starters') },
        { _id: `item4-${restaurantId}`, name: 'Soup of the Day', description: 'Chef daily soup selection', price: 1.29, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item4', 'Starters') },
        { _id: `item5-${restaurantId}`, name: 'Caesar Salad', description: 'Romaine lettuce with Caesar dressing', price: 1.69, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item5', 'Starters'), isVegetarian: true },
        { _id: `item26-${restaurantId}`, name: 'Chicken Nuggets', description: 'Crispy chicken nuggets with sauce', price: 1.79, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item26', 'Starters') },
        { _id: `item27-${restaurantId}`, name: 'Onion Rings', description: 'Golden fried onion rings', price: 1.49, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item27', 'Starters'), isVegetarian: true },
        { _id: `item28-${restaurantId}`, name: 'Garlic Bread', description: 'Toasted bread with garlic butter', price: 0.99, category: 'Starters', image: getUniqueMenuItemImage(restaurantId, 'item28', 'Starters'), isVegetarian: true },
        { _id: `item6-${restaurantId}`, name: 'Signature Main Course', description: 'Restaurant signature dish', price: 3.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item6', 'Main Course') },
        { _id: `item7-${restaurantId}`, name: 'Grilled Chicken', description: 'Herb-marinated grilled chicken', price: 2.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item7', 'Main Course') },
        { _id: `item8-${restaurantId}`, name: 'Beef Steak', description: 'Juicy grilled beef steak', price: 4.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item8', 'Main Course') },
        { _id: `item9-${restaurantId}`, name: 'Fish Fillet', description: 'Pan-seared fish with herbs', price: 3.79, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item9', 'Main Course') },
        { _id: `item10-${restaurantId}`, name: 'Vegetable Curry', description: 'Mixed vegetables in curry sauce', price: 2.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item10', 'Main Course'), isVegetarian: true, spicyLevel: 1 },
        { _id: `item29-${restaurantId}`, name: 'Chicken Burger', description: 'Grilled chicken burger with fries', price: 2.99, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item29', 'Main Course') },
        { _id: `item30-${restaurantId}`, name: 'Fried Rice', description: 'Wok-fried rice with vegetables', price: 2.29, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item30', 'Main Course'), isVegetarian: true },
        { _id: `item31-${restaurantId}`, name: 'Chicken Sandwich', description: 'Grilled chicken sandwich', price: 2.49, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item31', 'Main Course') },
        { _id: `item32-${restaurantId}`, name: 'Pasta Primavera', description: 'Pasta with fresh vegetables', price: 2.79, category: 'Main Course', image: getUniqueMenuItemImage(restaurantId, 'item32', 'Main Course'), isVegetarian: true },
        { _id: `item11-${restaurantId}`, name: 'French Fries', description: 'Crispy golden fries', price: 0.99, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item11', 'Sides'), isVegetarian: true },
        { _id: `item12-${restaurantId}`, name: 'Garlic Bread', description: 'Toasted bread with garlic', price: 0.79, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item12', 'Sides'), isVegetarian: true },
        { _id: `item13-${restaurantId}`, name: 'Steamed Rice', description: 'Plain steamed rice', price: 0.99, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item13', 'Sides'), isVegetarian: true },
        { _id: `item14-${restaurantId}`, name: 'Mixed Vegetables', description: 'Seasonal steamed vegetables', price: 1.19, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item14', 'Sides'), isVegetarian: true },
        { _id: `item15-${restaurantId}`, name: 'Mashed Potatoes', description: 'Creamy mashed potatoes', price: 0.99, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item15', 'Sides'), isVegetarian: true },
        { _id: `item33-${restaurantId}`, name: 'Coleslaw', description: 'Fresh cabbage and carrot salad', price: 0.89, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item33', 'Sides'), isVegetarian: true },
        { _id: `item34-${restaurantId}`, name: 'Corn Salad', description: 'Sweet corn with herbs', price: 1.09, category: 'Sides', image: getUniqueMenuItemImage(restaurantId, 'item34', 'Sides'), isVegetarian: true },
        { _id: `item16-${restaurantId}`, name: 'Chocolate Cake', description: 'Rich chocolate cake', price: 1.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item16', 'Desserts'), isVegetarian: true },
        { _id: `item17-${restaurantId}`, name: 'Fruit Salad', description: 'Fresh seasonal fruits', price: 1.19, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item17', 'Desserts'), isVegetarian: true },
        { _id: `item18-${restaurantId}`, name: 'Ice Cream', description: 'Vanilla, chocolate, or strawberry', price: 0.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item18', 'Desserts'), isVegetarian: true },
        { _id: `item19-${restaurantId}`, name: 'Apple Pie', description: 'Traditional apple pie', price: 1.39, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item19', 'Desserts'), isVegetarian: true },
        { _id: `item20-${restaurantId}`, name: 'Cheesecake', description: 'Creamy cheesecake slice', price: 1.49, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item20', 'Desserts'), isVegetarian: true },
        { _id: `item35-${restaurantId}`, name: 'Brownie', description: 'Fudgy chocolate brownie', price: 1.29, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item35', 'Desserts'), isVegetarian: true },
        { _id: `item36-${restaurantId}`, name: 'Cookies', description: 'Chocolate chip cookies (3 pcs)', price: 0.99, category: 'Desserts', image: getUniqueMenuItemImage(restaurantId, 'item36', 'Desserts'), isVegetarian: true },
        { _id: `item21-${restaurantId}`, name: 'Soft Drinks', description: 'Assorted sodas', price: 0.79, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item21', 'Beverages'), isVegetarian: true },
        { _id: `item22-${restaurantId}`, name: 'Fresh Juice', description: 'Seasonal fruit juice', price: 1.19, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item22', 'Beverages'), isVegetarian: true },
        { _id: `item23-${restaurantId}`, name: 'Coffee', description: 'Freshly brewed coffee', price: 0.99, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item23', 'Beverages'), isVegetarian: true },
        { _id: `item24-${restaurantId}`, name: 'Iced Tea', description: 'Refreshing iced tea', price: 0.79, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item24', 'Beverages'), isVegetarian: true },
        { _id: `item25-${restaurantId}`, name: 'Hot Chocolate', description: 'Rich hot chocolate with marshmallows', price: 1.19, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item25', 'Beverages'), isVegetarian: true },
        { _id: `item37-${restaurantId}`, name: 'Milkshake', description: 'Thick vanilla milkshake', price: 1.49, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item37', 'Beverages'), isVegetarian: true },
        { _id: `item38-${restaurantId}`, name: 'Lemonade', description: 'Fresh squeezed lemonade', price: 0.89, category: 'Beverages', image: getUniqueMenuItemImage(restaurantId, 'item38', 'Beverages'), isVegetarian: true },
        { _id: `item39-${restaurantId}`, name: 'Tomato Soup', description: 'Creamy tomato soup with herbs', price: 1.49, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item39', 'Soups'), isVegetarian: true },
        { _id: `item40-${restaurantId}`, name: 'Chicken Soup', description: 'Clear chicken broth with vegetables', price: 1.79, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item40', 'Soups') },
        { _id: `item41-${restaurantId}`, name: 'Mushroom Soup', description: 'Creamy mushroom soup', price: 1.69, category: 'Soups', image: getUniqueMenuItemImage(restaurantId, 'item41', 'Soups'), isVegetarian: true },
        { _id: `item42-${restaurantId}`, name: 'Grilled Salmon', description: 'Fresh salmon with lemon', price: 4.99, category: 'Grilled Items', image: getUniqueMenuItemImage(restaurantId, 'item42', 'Grilled Items') },
        { _id: `item43-${restaurantId}`, name: 'BBQ Chicken', description: 'Grilled chicken with BBQ sauce', price: 3.49, category: 'Grilled Items', image: getUniqueMenuItemImage(restaurantId, 'item43', 'Grilled Items') },
        { _id: `item44-${restaurantId}`, name: 'Grilled Vegetables', description: 'Mixed grilled seasonal vegetables', price: 2.29, category: 'Grilled Items', image: getUniqueMenuItemImage(restaurantId, 'item44', 'Grilled Items'), isVegetarian: true },
        { _id: `item45-${restaurantId}`, name: 'Lamb Chops', description: 'Herb-crusted lamb chops', price: 5.99, category: 'Grilled Items', image: getUniqueMenuItemImage(restaurantId, 'item45', 'Grilled Items') }
      ]
    }
  };
  
  return menus[menuType] || menus.default;
};

export default getRestaurantMenu;